name: Publish package
on: 
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: |
            - args: [--no-frozen-lockfile, --strict-peer-dependencies]

      - name: Build library
        run: pnpm build

      - name: Publish package
        run: pnpm publish --access=publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}